// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InvoicesManagementSystem.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace InvoicesManagementSystem.Data
{
    public partial interface ISalesDbContextProcedures
    {
        Task<int> CalculateTotalPriceAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
