// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InvoicesManagementSystem.Models
{
    public partial class Invoice_Detail
    {
        [Key]
        public int InvoiceID { get; set; }
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string ItemName { get; set; }
        public int? PricePerUnit { get; set; }
        public int? Quantity { get; set; }
        public int? ItemTotalPrice { get; set; }

        [ForeignKey("InvoiceID")]
        [InverseProperty("Invoice_Details")]
        public virtual Invoice Invoice { get; set; }
    }
}